### ISSUE TITLE
Adding support for ô , ö , ä , ů , and ü ?

### ISSUE THREAD

**Issue by marek-lach** [joeycastillo/babel#2]
Please consider adding support for the special characters of the _Slovak_ alphabet `ô` and `ä` , as well as a special character of the _Czech_ alphabet `ö`, `ů` and `ü`.

Thank you,
M

**Comment by joeycastillo** [comment]
Hi and sorry for the delay in responding to this; I must not have noticed the issue come in. 

I believe that Babel already supports all of these characters, as they are in the basic multilingual plane, which GNU Unifont has 100% coverage of. If you have any issues using them in babel, please reopen this issue and let me know. thanks!
